apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfbcs-app
  namespace: home-lewis
spec:
  replicas: 2
  selector:
    matchLabels:
     app: nfbcs-app
  template:
    metadata:
      labels:
        app: nfbcs-app
    spec:
      containers:
      - name: nfbcs-app
        image: lewislwood/nfbcs-app:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
 name: nfbcs-app
 namespace: home-lewis
spec:
  type: NodePort
  selector:
    app: nfbcs-app
  ports:
    - port: 3000
      protocol: TCP

      targetPort: 3000
      nodePort: 31031
      