apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfbcs-api
  namespace: home-lewis
spec:
  replicas: 2
  selector:
    matchLabels:
     app: nfbcs-api
  template:
    metadata:
      labels:
        app: nfbcs-api
    spec:
      containers:
      - name: nfbcs-api
        image: lewislwood/nfbcs-api:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: nfbcs-api
  namespace: home-lewis
spec:
  type: NodePort
  selector:
    app: nfbcs-api
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 31030
        
